# Generated by Django 3.2.7 on 2021-09-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('evolution_chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_chain', to='pokeapp.evolutionchain')),
                ('stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokeapp.stats')),
            ],
        ),
        migrations.AddField(
            model_name='evolutionchain',
            name='evols_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evols_to', to='pokeapp.pokemon'),
        ),
        migrations.AddField(
            model_name='evolutionchain',
            name='prevols_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevols_to', to='pokeapp.pokemon'),
        ),
    ]
